name: Deploy DAG and PySpark Script

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: "boxwood-axon-470816-b1
      - name: Upload DAG to Composer
        run: gsutil cp dags/ev_pipeline_dag.py gs://us-central1-etl-airflow-33be8bc7-bucket/dags/

      - name: Upload PySpark script
        run: gsutil cp scripts/etl_ev.py gs://ev-market-data/scripts/etl_ev.py
